<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-34P0QRN" failures="1" tests="7" name="com.app.execution.Execution" time="13.620" errors="0" timestamp="2022-09-05T23:31:40 PDT" skipped="0">
  <testcase classname="com.app.execution.Execution" name="loginUsingIncorrectCredentials" time="2.464"/>
  <system-out/>
  <testcase classname="com.app.execution.Execution" name="loginUsingCorrectCredentials" time="1.583"/>
  <system-out/>
  <testcase classname="com.app.execution.Execution" name="availableBalanceValidation" time="1.749">
    <failure message="Balance is not matching expected [$114282.44] but found [$294102.44]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Balance is not matching expected [$114282.44] but found [$294102.44]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.app.pageexe.HomePageExe.validateAccountBalance(HomePageExe.java:23)
at com.app.execution.Execution.availableBalanceValidation(Execution.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- availableBalanceValidation -->
  <system-out/>
  <testcase classname="com.app.execution.Execution" name="fundTransferandValidation" time="1.952"/>
  <system-out/>
  <testcase classname="com.app.execution.Execution" name="viewTransactionHistory" time="0.983"/>
  <system-out/>
  <testcase classname="com.app.execution.Execution" name="fillTheOnlineForm" time="3.795"/>
  <system-out/>
  <testcase classname="com.app.execution.Execution" name="signOffValidation" time="1.094"/>
  <system-out/>
</testsuite> <!-- com.app.execution.Execution -->
